### ISSUE TITLE
build-plugin

### ISSUE THREAD

**Issue by knobo** [knobo/tellstick-server#2]
```
(env) ❰knobo❙~/usr/src/telldus/tellstick-server(git:master)❱✔≻ ./tellstick.sh build-plugin ~/prog/python/cherrypy/knobo
Building plugin /home/knobo/prog/python/cherrypy/knobo
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/knobo/usr/src/telldus/tellstick-server/build/env/lib/python2.7/site-packages/gnupg.py", line 861, in _read_response
    result.handle_status(keyword, value)
  File "/home/knobo/usr/src/telldus/tellstick-server/build/env/lib/python2.7/site-packages/gnupg.py", line 314, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'VERIFICATION_COMPLIANCE_MODE'


```

**Comment by knobo** [comment]
Editing manually this file:
`build/env/lib/python2.7/site-packages/gnupg.py`

``` diff
--- old/(gnupg.py	2020-06-05 13:04:31.388793000 +0200
+++ new/gnupg.py	2020-06-05 13:00:47.140093137 +0200
@@ -246,7 +246,7 @@
                      "FILE_DONE", "PKA_TRUST_GOOD", "PKA_TRUST_BAD", "BADMDC",
                      "GOODMDC", "NO_SGNR", "NOTATION_NAME", "NOTATION_DATA",
                      "PROGRESS", "PINENTRY_LAUNCHED", "NEWSIG",
-                     "KEY_CONSIDERED"):
+                     "KEY_CONSIDERED", "VERIFICATION_COMPLIANCE_MODE"):
             pass
         elif key == "BADSIG":  # pragma: no cover
             self.valid = False
```

I don't know what consequences this will have, though. I don't know anything about gnupg

**Comment by knobo** [comment]
```
(env) ❰knobo❙~/usr/src/telldus/tellstick-server(git:master)❱✘≻ rm -Rf ~/prog/python/cherrypy/knobo/build
(env) ❰knobo❙~/usr/src/telldus/tellstick-server(git:master)❱✔≻ ./tellstick.sh build-plugin ~/prog/python/cherrypy/knobo
Building plugin /home/knobo/prog/python/cherrypy/knobo
(env) ❰knobo❙~/usr/src/telldus/tellstick-server(git:master)❱✔≻ 
```
![image](https://user-images.githubusercontent.com/89921/83869974-b7f6e780-a72d-11ea-8b06-327c365dced6.png)

**Comment by mickeprag** [comment]
Yes, this issue happens when there is a version mismatch between python-gnupg and the installed gnupg. Try upgrading python-gnupg and see is the issue will be resolved:
```
tellstick.sh shell
pip install -U python-gnupg
```

Your workaround os probably fine as well.

For future issues, please open a direct support issue with our support since creating issues in private repository will easily be missed.

**Comment by knobo** [comment]
Thanx. I was documenting this for my own sake, until I got the tellstick-server to run on my own computer. This "Error imporint plugin" is not from my own computer but my TellStick ZNet Lite Net V2 unit.
So that means that I have to install the same version of python-gnupg on my repo as is running on my unit. 
How do I find out which version is running on my TellStick?

**Comment by mickeprag** [comment]
The error message from your plugin is not related to the gnupg version. You need to contact the support to get your key imported to your TellStick before self-signed plugins can be loaded.

**Comment by knobo** [comment]
But I do get the same error when running tellstick-server on my local computer. How do I add my gpg key to the server?

**Comment by mickeprag** [comment]
On your local computer I recommend you "install" the plugin using `tellstick.sh` instead of uploading it as a packaged plugin. When it's installed you do not need to repack it when you edit your files. The service will also restart itself automatically when a file is changed.

If your really want to upload it as a plugin, remove this line:
https://github.com/knobo/tellstick-server/blob/master/plugin-loader/src/pluginloader/Loader.py#L190
